# Generated by Django 5.2.10 on 2026-01-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='residente',
            options={'verbose_name': 'Moradores', 'verbose_name_plural': 'Moradores'},
        ),
    ]
