# Generated by Django 5.2.10 on 2026-01-31 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_options_alter_residente_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='password_gate',
            new_name='gate_password',
        ),
    ]
