# Generated by Django 5.2.10 on 2026-02-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_password_gate_customuser_gate_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residente',
            old_name='to_walk',
            new_name='floor_number',
        ),
    ]
